cactid test (#6309)
* Update syntax.yml

For plugins with dedicated config files they need to be moved or else the install will fail

* fix cp command

* Update syntax.yml

* Add a walk of the localhost

* Skip snmp for PHP7.0--

* add some cli script tests

* rename test

* Change the device ip and template

* Create cactid.service

* Add cactid

* cactid

need to test the daemon after the DB is initilized

* Update syntax.yml

* Update syntax.yml

- Add Intropage plugin
- Add check that the cactid daemon started
- Run Cacti poller

* fix poller path

* put test in the proper place

run the poller after the test device has been created

---------

Co-authored-by: TheWitness <thewitness@cacti.net>

diff --git a/.github/workflows/syntax.yml b/.github/workflows/syntax.yml
--- a/.github/workflows/syntax.yml
+++ b/.github/workflows/syntax.yml
@@ -90,6 +90,12 @@ jobs:
         owner: 'Cacti'
         repository: 'plugin_mactrack'
 
+    - name: Checkout Intropage Plugin
+      uses: GuillaumeFalourd/clone-github-repo-action@v2
+      with:
+        owner: 'Cacti'
+        repository: 'plugin_intropage'
+
     - name: Checkout FlowView Plugin
       uses: GuillaumeFalourd/clone-github-repo-action@v2
       with:
@@ -115,6 +121,7 @@ jobs:
         mv plugin_mactrack ${{ github.workspace }}/plugins/mactrack
         mv plugin_audit ${{ github.workspace }}/plugins/audit
         mv plugin_flowview ${{ github.workspace }}/plugins/flowview
+        mv plugin_intropage ${{ github.workspace }}/plugins/intropage
         mv plugin_syslog ${{ github.workspace }}/plugins/syslog
         # With syslog we have to enable batch installs using the lines below
         cd ${{ github.workspace }}/plugins/syslog
@@ -189,6 +196,22 @@ jobs:
         sudo chmod 777 ${{ github.workspace }}/include/config.php
         cat ${{ github.workspace}}/include/config.php
 
+
+
+    - name: Setup Cacti Daemon
+      if: ${{ '5.4' != matrix.php && '7.0' != matrix.php }} # removed old php from page tests
+      run: |
+        sudo cp ${{ github.workspace }}/tests/tools/cactid.service /etc/systemd/system/cactid.service
+        sudo systemctl enable cactid
+        sudo systemctl start cactid
+        sudo systemctl status cactid
+        if ! systemctl is-active --quiet cactid; then
+          echo "Cacti daemon failed to start"
+          exit 1
+        fi
+
+
+
     - name: Check install code for validity
       if: ${{ '5.4' != matrix.php && '7.0' != matrix.php }} # removed old php from page tests
       run: |
@@ -211,7 +234,7 @@ jobs:
       if: ${{ '5.4' != matrix.php && '7.0' != matrix.php }} # removed old php from page tests
       run: |
         cd ${{ github.workspace }}
-        sudo php cli/plugin_manage.php --plugin=thold --plugin=monitor --plugin=mactrack --plugin=audit --plugin=flowview --plugin=syslog --install --enable --allperms
+        sudo php cli/plugin_manage.php --plugin=thold --plugin=intropage --plugin=monitor --plugin=mactrack --plugin=audit --plugin=flowview --plugin=syslog --install --enable --allperms
 
     - name: Add Device for Moc Test, Check CLI scripts for Errors
       if: ${{ '5.4' != matrix.php && '7.0' != matrix.php }} # removed old php from page tests
@@ -220,6 +243,17 @@ jobs:
         sudo php cli/add_device.php --description=test_device --ip=127.0.0.1 --template=24
         sudo php cli/rebuild_poller_cache.php --debug
         sudo php cli/poller_reindex_hosts.php --id=all --debug
+
+
+    - name: Run Cacti poller
+      if: ${{ '5.4' != matrix.php && '7.0' != matrix.php }} # removed old php from page tests
+      run: |
+        sudo php ${{ github.workspace }}/poller.php --poller=1 --force --debug
+        if ! grep -q "SYSTEM STATS" ${{ github.workspace }}/log/cacti.log; then
+          echo "Cacti poller did not finish successfully"
+          exit 1
+        fi
+
 
     - name: Check all pages using recursive wget
       if: ${{ '5.4' != matrix.php && '7.0' != matrix.php }} # removed old php from page tests
