Fix more style issues.

diff --git a/.github/workflows/syntax.yml b/.github/workflows/syntax.yml
--- a/.github/workflows/syntax.yml
+++ b/.github/workflows/syntax.yml
@@ -182,13 +182,13 @@ jobs:
         # With syslog we have to enable batch installs using the lines below
         cd ${{ github.workspace }}/plugins/syslog
         cp -p config.php.dist config.php
-        sed -i 's/\/\/\$syslog_install_options/\$syslog_install_options/g' config.php
+        sed -i "s/\/\/\$syslog_install_options/\$syslog_install_options/g" config.php
 
     - name: Move plugin config files
       run: |
         cp -p ${{ github.workspace }}/plugins/flowview/config.php.dist ${{ github.workspace }}/plugins/flowview/config.php
         cp -p ${{ github.workspace }}/plugins/syslog/config.php.dist ${{ github.workspace }}/plugins/syslog/config.php
-        sed -i 's/\/\/\$/\$/g' ${{ github.workspace }}/plugins/syslog/config.php
+        sed -i "s/\/\/\$/\$/g" ${{ github.workspace }}/plugins/syslog/config.php
 
     - name: Run apt-get update
       run: sudo apt-get -y update
@@ -216,7 +216,8 @@ jobs:
       
     - name: Configure Apache Site
       run: |
-        cat ${{ github.workspace }}/tests/tools/cacti.conf | sed -r "s#GITHUB_WORKSPACE#${{ github.workspace }}#g" > /tmp/cacti.conf
+        cp ${{ github.workspace }}/tests/tools/cacti.conf /tmp/cacti.conf
+        sed -i "s#GITHUB_WORKSPACE#${{ github.workspace }}#g" /tmp/cacti.conf
         sudo cp /tmp/cacti.conf /etc/apache2/sites-available/000-default.conf
 
     - name: Restart Apache2
@@ -228,7 +229,7 @@ jobs:
       run: |
         echo -e "[client]\nuser = root\npassword = cactiroot\nhost = 127.0.0.1\nmax_allowed_packet = 500000000\n" >> ~/.my.cnf
         cat ~/.my.cnf
-        mysql $MYSQL_AUTH_USR -e 'CREATE DATABASE IF NOT EXISTS cacti;'
+        mysql $MYSQL_AUTH_USR -e "CREATE DATABASE IF NOT EXISTS cacti;"
         mysql $MYSQL_AUTH_USR -e "CREATE USER 'cactiuser'@'localhost' IDENTIFIED BY 'cactiuser';"
         mysql $MYSQL_AUTH_USR -e "GRANT ALL PRIVILEGES ON cacti.* TO 'cactiuser'@'localhost';"
         mysql $MYSQL_AUTH_USR -e "FLUSH PRIVILEGES;"
@@ -266,7 +267,11 @@ jobs:
         sudo php tests/tools/check_xml_syntax.php
 
     - name: Check Poller Script Syntax after Package Import
-      run: find ${{ github.workspace }}/scripts -name '*.php' -exec php -l {} 2>&1 \; | grep -iv 'no syntax errors detected' && exit 1
+      run: 
+        if [[ $(find ${{ github.workspace }}/scripts -name '*.php' -exec php -l {} 2>&1 \; | grep -iv 'no syntax errors detected') ]]; then
+          echo "Syntax errors found in php code"
+          exit 1
+        fi
 
     - name: Check that all CLI scripts have a valid --version flag
       run: |
@@ -291,7 +296,10 @@ jobs:
     - name: Check all perl scripts for syntax errors
       run: |
         cd ${{ github.workspace }}
-        find scripts -name '*.pl' -exec perl -c {} 2>&1 \; | grep -iv 'syntax OK' && exit 1
+        if [[ $(find scripts -name '*.pl' -exec perl -c {} 2>&1 \; | grep -iv 'syntax OK') ]]; then 
+          echo "Syntax errors found in perl code"
+          exit 1
+        fi
 
     - name: Audit the Installation Schema
       run: |
@@ -313,7 +321,7 @@ jobs:
     - name: Run Cacti poller
       run: |
         sudo php ${{ github.workspace }}/poller.php --poller=1 --force --debug
-        if ! grep -q "SYSTEM STATS" ${{ github.workspace }}/log/cacti.log; then
+        if [[ ! $(grep -q "SYSTEM STATS" ${{ github.workspace }}/log/cacti.log) ]]; then
           echo "Cacti poller did not finish successfully"
           exit 1
         fi
